"""Fitted straight-flank sliding spline pairs, not factory tooth dimensions.
Profiles below are the exact cap/side geometry consumed by Blender.
"""
from pathlib import Path
import json,math
from planetary_geometry import circle
from shapely.geometry import Polygon,box
from shapely.affinity import rotate
from shapely.ops import unary_union
from shapely import constrained_delaunay_triangles
from clutch_groove_geometry import grooved_surface
ROOT=Path(__file__).resolve().parents[1]
D=json.loads((ROOT/'work/transmission/poses.json').read_text());out={};reports=[];surfaces={}
def teeth(root,tip,width,count,phase=0):
    return unary_union([rotate(box(root,-width/2,tip,width/2),phase+j*math.tau/count,origin=(0,0),use_radians=True) for j in range(count)])
def data(poly):
    assert poly.is_valid and poly.geom_type=='Polygon'
    rings=[list(poly.exterior.coords)[:-1]]+[list(h.coords)[:-1] for h in poly.interiors]
    points=[p for ring in rings for p in ring];ids={tuple(p):i for i,p in enumerate(points)}
    caps=[[ids[tuple(p)] for p in list(t.exterior.coords)[:-1]] for t in constrained_delaunay_triangles(poly).geoms]
    return dict(points=points,caps=caps,rings=[len(r) for r in rings])
for name,p in D['clutches'].items():
    ri,ro=p['inner'],p['outer'];n_inner,n_outer=24,32;clearance=.00008
    inner_male=teeth(ri-.0015,ri+.002,.0028,n_inner)
    inner_female=teeth(ri-.0015,ri+.0022,.0028+2*clearance,n_inner)
    outer_male=teeth(ro-.0005,ro+.003,.0034,n_outer,math.pi/n_outer)
    outer_female=teeth(ro-.0005,ro+.0032,.0034+2*clearance,n_outer,math.pi/n_outer)
    hub=circle(ri-.001,384).union(inner_male).difference(circle(ri-.007,384))
    friction=circle(ro,384).difference(circle(ri,384).union(inner_female))
    steel=circle(ro,384).union(outer_male).difference(circle(ri+.003,384))
    drum=circle(ro+.008,384).difference(circle(ro+.001,384).union(outer_female))
    # Teeth only occupy the axial span shared by the sliding friction plates.
    pitch=D['contact']['plateThickness']+D['contact']['plateGap'];t=D['contact']['plateThickness']
    start=p['start'] if p['direction']==1 else p['start']-(p['count']-1)*pitch
    travel=D['contact']['pistonGap']+(p['count']-1)*D['contact']['plateGap']
    piston_full=p['start']-p['direction']*.005+p['direction']*travel
    lo=start+pitch-t/2;hi=start+(p['count']-2)*pitch+t/2
    if p['direction']==1:lo=max(lo,piston_full+.001)
    else:hi=min(hi,piston_full-.001)
    polygons=dict(hub=hub,friction=friction,steel=steel,drum=drum)
    entry={k:data(v) for k,v in polygons.items()};entry['hubLo']=lo;entry['hubHi']=hi
    family=p['family']
    if family not in surfaces:
        surface=D['surfaces']
        surfaces[family]=grooved_surface(friction,steel,ri,ro,t,surface[family],surface['depth'],surface['liningThickness'])
    entry['frictionGrooved']=surfaces[family]
    entry['pusherCount']=p['springCount']
    for j in range(p['springCount']):
        a=j*math.tau/p['springCount']+.022;b=(j+1)*math.tau/p['springCount']-.022
        sector=Polygon([(0,0)]+[(.4*math.cos(a+(b-a)*k/32),.4*math.sin(a+(b-a)*k/32)) for k in range(33)])
        entry['drumSegment'+str(j)]=data(drum.intersection(sector))
    # Independently check radial material exclusion and bounded flank backlash.
    assert hub.intersection(friction).area<1e-12
    assert drum.intersection(steel).area<1e-12
    assert hub.intersection(steel).area<1e-12
    assert drum.intersection(friction).area<1e-12
    inner_interference=hub.intersection(rotate(friction,.006,origin=(0,0),use_radians=True)).area
    outer_interference=drum.intersection(rotate(steel,.006,origin=(0,0),use_radians=True)).area
    assert min(inner_interference,outer_interference)>1e-8
    minimum_overlap=1
    for i in range(101):
        stroke=travel*i/100
        for j in range(1,p['count'],2):
            ordinal=j if p['direction']==1 else p['count']-1-j
            shift=p['direction']*min((p['count']-1-ordinal)*D['contact']['plateGap'],max(0,stroke-D['contact']['pistonGap']-ordinal*D['contact']['plateGap']))
            x=start+j*pitch+shift
            minimum_overlap=min(minimum_overlap,min(x+t/2,hi)-max(x-t/2,lo))
    assert minimum_overlap>.0006
    entry['spec']=dict(innerCount=n_inner,outerCount=n_outer,flankClearance=clearance,status='Fitted straight-flank spline dimensions; not factory count or manufacturing tolerance.')
    out[name]=entry;reports.append(dict(pack=name,minAxialEngagementMM=minimum_overlap*1000,innerSlipInterferenceMM2=inner_interference*1e6,outerSlipInterferenceMM2=outer_interference*1e6,**entry['spec']))
(ROOT/'work/transmission/clutch-splines.json').write_text(json.dumps(out))
(ROOT/'outputs/clutch-spline-profile-checks.json').write_text(json.dumps(reports,indent=2));print(json.dumps(reports,indent=2))
metrics={name:surface['metrics'] for name,surface in surfaces.items()}
(ROOT/'lib/clutchSurfaceMetrics.ts').write_text('// Generated by scripts/prepare-clutch-splines.py from the actual contact lands.\n// Uniform normal pressure on lands; no oil-film/thermal/wear or factory calibration.\nexport const CLUTCH_SURFACE_METRICS = '+json.dumps(metrics,indent=2)+' as const;\n',encoding='utf-8')
(ROOT/'outputs/clutch-groove-profile-checks.json').write_text(json.dumps({name:{'vertices':len(s['vertices']),'faces':len(s['faces']),'cells':s['cells'],**s['metrics']} for name,s in surfaces.items()},indent=2));print(json.dumps(metrics,indent=2))
