// Generated by scripts/prepare-clutch-splines.py from the actual contact lands.
// Uniform normal pressure on lands; no oil-film/thermal/wear or factory calibration.
export const CLUTCH_SURFACE_METRICS = {
    "large": {
        "area": 0.03897116638886209,
        "meanRadius": 0.19003989701108753,
        "grooveArea": 0.0029031678188861446,
        "depth": 0.00018,
        "liningThickness": 0.0003
    },
    "small": {
        "area": 0.013879754524318708,
        "meanRadius": 0.06571316233794625,
        "grooveArea": 0.0006220904279671845,
        "depth": 0.00018,
        "liningThickness": 0.0003
    }
};
