import bpy,sys,json,hashlib,time
from pathlib import Path
import numpy as np
root=Path('/workspace/scratch/a29d03198654'); inp=root/'maz-step-installation-fit-20261001/installation-failure-summary.json'; candidate=root/'maz-native-axis-controls-20261001/MAZ543A_Native_Barrel_Axis_Controls.blend'; out=Path(__file__).with_name('witness-readback.json')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
expected='3b230c12077828102776eb70e5e87aaa47b8b72f5e681589745ad8610a18c03f';before=sha(candidate);assert before==expected
bpy.ops.wm.open_mainfile(filepath=str(candidate));assert bpy.app.version==(4,5,13);assert not bpy.context.preferences.filepaths.use_scripts_auto_execute
for n in ['cab_pivot_002','cab_pivot_003','cab_pivot_006','cab_pivot_007']:assert bpy.data.objects[n]['open_angle_deg']==0
bpy.context.view_layer.update();dg=bpy.context.evaluated_depsgraph_get();j=json.loads(inp.read_text());rep=json.loads((inp.parent/'attempt-05/native/fit-report.json').read_text());box=next(x['bounds_m'] for x in rep['reconstructed_study'] if x['name']=='TREAD_REGION_2__plain_envelope');lo,hi=np.asarray(box);records=[]
for row in j['wheel_surface_witnesses']:
 o=bpy.data.objects[row['object']].evaluated_get(dg);m=o.to_mesh();m.calc_loop_triangles();tri=m.loop_triangles[row['triangle']];v=np.array([m.vertices[i].co[:] for i in tri.vertices],dtype=np.float64);w=np.array(o.matrix_world,dtype=np.float64);v=v@w[:3,:3].T+w[:3,3];p=np.array(row['point_world_m']);e=np.column_stack((v[1]-v[0],v[2]-v[0]));uv=np.linalg.lstsq(e,p-v[0],rcond=None)[0];bary=np.array([1-uv.sum(),uv[0],uv[1]]);recon=bary@v;error=float(np.linalg.norm(recon-p));margin=float(min((p-lo).min(),(hi-p).min()));assert error<1e-10 and bary.min()>-1e-9 and bary.max()<1+1e-9;assert margin>2e-5 and margin==row['minimum_axis_box_margin_m'];records.append({'object':row['object'],'triangle':row['triangle'],'triangle_world_m':v.tolist(),'point_world_m':p.tolist(),'barycentric':bary.tolist(),'point_reconstruction_error_m':error,'minimum_box_axis_margin_m':margin});o.to_mesh_clear()
assert len(records)==8 and len({x['object'] for x in records})==8;after=sha(candidate);assert before==after
out.write_text(json.dumps({'status':'EIGHT_NATIVE_TRIANGLE_WITNESSES_IN_TREAD_BOX_VERIFIED','script_sha256':sha(Path(__file__)),'input_summary_sha256':sha(inp),'candidate_sha256':after,'candidate_unchanged':True,'scene_not_saved':True,'model_parts_not_moved':True,'box_bounds_m':box,'records':records,'limits':'Eight selected witnesses in actual native evaluated original triangles, one saved closed pose. Margins are point-to-box-face coordinate margins, not penetration depth or whole-vehicle clearance. No new continuous or physical acceptance.'},indent=2)+'\n');print('EIGHT_NATIVE_WITNESSES_VERIFIED')
